- name: Commit and push changes
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "aifordiscord"
          git config user.email "aifordiscoord@gmail.com"
          git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/aifordiscord/aifordiscord.git
          git add README.md
          git commit -m "🔄 Auto-update Featured Projects" || echo "No changes"
          git push origin HEAD:main
